from pathlib import Path
p=Path('scripts/tools/check_stair_rewards.py')
s=p.read_text().replace('root_pos_w=torch.tensor([[-.45, 0., .4]]), root_lin_vel_b=', 'root_pos_w=torch.tensor([[-.45, 0., .4]]), root_quat_w=torch.tensor([[1.,0.,0.,0.]]), root_lin_vel_b=')
p.write_text(s)
p=Path('scripts/tools/check_gait_refinement.py')
s=p.read_text().replace('ns = dict(torch=torch,', 'ns = dict(np=__import__("numpy"), torch=torch,').replace('quat_apply=quat_apply, yaw_quat=yaw_quat,', 'quat_apply=quat_apply, quat_apply_inverse=lambda q,v: quat_apply(q*torch.tensor([1.,-1.,-1.,-1.]),v), yaw_quat=yaw_quat,')
s=s.replace("('front_normal_up', dict(down=False), False)", "('front_normal_up', dict(down=False), False)")
s=s.replace("('front_folded_swing', dict(down=False,folded=True,swing=True), False)", "('front_folded_swing', dict(down=False,folded=True,swing=True), True)")
s=s.replace("assert result['front_landing_buffer_cost'] == 0", "assert result['front_landing_buffer_cost'] > 0")
s=s.replace("assert result['front_riser_face_only_cost'] == 0", "assert result['front_riser_face_only_cost'] > 0")
s=s.replace("(.4,2.2,True)", "(.4,2.2,True)")
s=s.replace("    s = advance()\n    result['intermediate_pair_event']", "    advance()\n    s = advance()\n    result['intermediate_pair_event']")
s=s.replace("s = ns['ascent_state'](env,wheels,scanner,contact)\n        name = 'real_scan_next_step'", "ns['ascent_state'](env,wheels,scanner,contact)\n        env.common_step_counter += 1\n        s = ns['ascent_state'](env,wheels,scanner,contact)\n        name = 'real_scan_next_step'")
p.write_text(s)
